export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";

export const UPDATE_CURRENT_BURST = "UPDATE_CURRENT_BURST";
export const UPDATE_BURST = "UPDATE_BURST";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const LOAD_TASKS = "LOAD_TASKS";
export const ADD_TO_TASK = "ADD_TO_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";
export const EDIT_TASK = "EDIT_TASK";
export const LOAD_STATS = "LOAD_STATS";
export const LOAD_ACTIVITY_FEED = "LOAD_ACTIVITY_FEED";
export const UPDATE_DATES = "UPDATE_DATES";
export const TOGGLE_SKIPPED = "TOGGLE_SKIPPED";
export const TOGGLE_SPLIT_TO_BURSTS = "TOGGLE_SPLIT_TO_BURSTS";
export const TOGGLE_SHOW_COMPLETED = "TOGGLE_SHOW_COMPLETED";

export const LOAD_WORKS = "LOAD_WORKS";
export const ADD_TO_WORKS = "ADD_TO_WORKS";
export const REMOVE_FROM_WORKS = "REMOVE_FROM_WORKS";
export const EDIT_WORK = "EDIT_WORK";
export const LOAD_BURSTS = "LOAD_BURSTS";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DISMISS_NOTIFICATION = "DISMISS_NOTIFICATION";
